app/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import views

app/student/views.py
import pymysql
from flask import Flask, render_template, jsonify, request, redirect, url_for, flash
from flask_login import login_required, current_user

from app import myUtils
from config import *
from app.models import *
from manage import config_name
from . import student

from .form import *
from app.data.dao.impl.DaoImpl import DaoImpl

USER_TYPE = 'student'
HOME_PAGE = 'main.index'
NO_PERMISSION_TEXT = '没有访问权限.'
CHECK_IN_HOST = '127.0.0.1'
CHECK_IN_PORT = '5000'
CHECK_IN_TYPE = 'student/check_in/'
CHECK_IN_URL_HEAD = 'http://' + CHECK_IN_HOST + ':' + CHECK_IN_PORT + '/' + CHECK_IN_TYPE

# 个人主页
@student.route('/my')
@login_required
def my():
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    print('uuid:' + uuid)
    student = DaoImpl.query_student_by_uuid(uuid)
    # 不存在该学生信息
    if student is None:
        flash('请完善个人信息.')
        return redirect(url_for('student.edit_info'))
    course_list = DaoImpl.query_course_by_stu_id(student.stu_id)
    return render_template('student/my.html', student=student, course_list=course_list)


# 个人信息编辑页面
@student.route('/edit_info', methods=['GET', 'POST'])
@login_required
def edit_info():
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    stu_id = myUtils.get_user_id(uuid)
    form = EditInfoForm()
    if form.validate_on_submit():
        stu_name = form.stu_name.data
        phone_number = form.phone_number.data
        email = form.email.data
        student = DaoImpl.query_student_by_uuid(uuid)
        # 不存在该学生信息，插入
        if student is None:
            DaoImpl.add_student(uuid, stu_id, stu_name, phone_number, email)
        # 存在该学生信息，修改
        else:
            DaoImpl.update_student_by_uuid(uuid, stu_name, phone_number, email)
        flash('编辑成功.')
        return redirect(url_for('student.my'))
    return render_template('student/edit_info.html', stu_id=stu_id, form=form)


# 加入课程
@student.route('/join_course', methods=['GET', 'POST'])
@login_required
def join_course():
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    stu_id = myUtils.get_user_id(uuid)
    if request.method == 'POST':
        # 加入课程
        data = request.get_json()
        course_id = data['course_id']
        DaoImpl.add_sc_by_course_id_and_stu_id(course_id, stu_id)
        flash('成功加入课程.')
        return jsonify({'result': 'ok'})

    # 获取未修读课程
    course_list = DaoImpl.query_course_not_taken_by_stu_id(stu_id)
    return render_template('student/join_course.html', course_list=course_list)


# 退出课程
@student.route('/quit_course', methods=['POST'])
@login_required
def quit_course():
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    stu_id = myUtils.get_user_id(uuid)
    data = request.get_json()
    course_id = data['course_id']
    DaoImpl.delete_sc_by_course_id_and_stu_id(course_id, stu_id)
    flash('已退出课程.')
    return jsonify({'result': 'ok'})


# 签到页面
@student.route('/check_in/<course_id>', methods=['GET', 'POST'])
@login_required
def check_in(course_id):
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    stu_id = myUtils.get_user_id(uuid)
    now_time = datetime.now()
    form = CheckInForm()
    if form.validate_on_submit():
        task_id = form.task_id.data
        task = DaoImpl.query_task_by_task_id(task_id)
        if task.end_time >= now_time:
            # 签到
            DaoImpl.add_check_in_record(stu_id, task_id)
            flash('签到成功.')
        else:
            # 拒绝签到
            flash('签到失败：不在签到时段.')
        return redirect(url_for('student.check_in', course_id=course_id))

    else:
        task_value = False
        sc = DaoImpl.query_sc_by_course_id_and_stu_id(course_id, stu_id)
        if sc is None:
            # 未修读此门课程
            flash('你未修读此门课程，无法签到.')
            return redirect(url_for(HOME_PAGE))
        task = DaoImpl.query_task_by_course_id_and_now_time(course_id)
        if task is None:
            print("task:null")
            flash('当前不在签到时段.')
        else:
            record = DaoImpl.query_check_in_record_by_task_id_and_uuid(task.task_id, myUtils.get_user_id(current_user.uuid))
            if record is None:
                # 未签到
                task_value = False
            else:
                # 已签到
                task_value = True
        course = DaoImpl.query_course_by_course_id(course_id)
        course_name = course.course_name
        teacher_id = course.teacher_id
        teacher = DaoImpl.query_teacher_by_teacher_id(teacher_id)
        teacher_name = teacher.teacher_name
        return render_template('student/check_in.html', course_id=course_id, course_name=course_name,
                               teacher_name=teacher_name, task=task, form=form, task_value=task_value)


# 查看签到记录页面
@student.route('/list_check_in_record')
@login_required
def list_check_in_record():
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    stu_id = myUtils.get_user_id(uuid)
    record_list = DaoImpl.query_check_in_record_by_stu_id(stu_id)
    return render_template('student/list_check_in_record.html', record_list=record_list)

app/templates/student/check_in.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Attendance {{ user_id }} {% endblock %}

{% block page_content %}

<div class="container" style="text-align:center">
    <h1>学生签到</h1>
    <br>
    <p>课程名称：{{ course_name }} </p>
    <p>课程号：{{ course_id }}</p>
    {% if task %}
    <p>签到任务ID：{{ task['task_id'] }}</p>
    <p>签到开始时间：{{ task['start_time'] }}</p>
    <p>签到结束时间：{{ task['end_time'] }}</p>
    <br>
    {% if task_value == False %}
    {{ wtf.quick_form(form) }}
    {% else %}
    <button type="button" class="btn btn-default" disabled="disabled">已签到</button>
    {% endif %}

</div>
{% else %}
<button type="button" class="btn btn-default" disabled="disabled">确认签到</button>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript">
        $("#task_id").attr("value", {{task['task_id']}});
        $("#task_id").attr("style", "display:none");
        $("#submit").attr("class", "btn btn-success");
        $(".control-label").attr("style", "display:none");

</script>
{% endblock %}

app/templates/student/edit_info.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - Login{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>学生个人信息修改</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
    <br>
</div>
{% endblock %}

app/templates/student/join_course.html
{% extends "base.html" %}

{% block title %}Attendance  - Login{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>学生个人选课</h1>
</div>
<div>
    <table class="table table-hover">
        <caption>选课</caption>
        <thead>
        <tr>
            <th>课程号</th>
            <th>课程名</th>
            <th>教师名</th>
            <th>选课</th>
        </tr>
        </thead>
        <tbody align="left">
        {% for course in course_list %}
        <tr>
            <td>{{ course['course_id'] }}</td>
            <td>{{ course['course_name'] }}</td>
            <td>{{ course['teacher_id'] }}</td>
            <td>
                <button type="button" onclick="join_course({{ course['course_id'] }})"
                        class="btn btn-default btn-xs">加入课程
                </button>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript">
        function join_course(course_id) {
            jQuery.ajax({
                url: '/student/join_course',
                dataType: "json",
                data: JSON.stringify({
                    "course_id": course_id,
                }),
                cache: false,
                contentType: "application/json",
                processData: false,
                method: 'POST',
                type: 'POST', // For jQuery < 1.9
                success: function (data) {
                    if (data.result == 'ok') {
                        window.location.reload()
                    }
                }
            });
        }

</script>
{% endblock %}

app/templates/student/list_check_in_record.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - Record{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>签到记录</h1>
</div>
<div>
    <table class="table table-hover">
        <caption>签到记录</caption>
        <thead>
        <tr>
            <th>课程号</th>
            <th>课程名</th>
            <th>签到时间</th>
        </tr>
        </thead>
        <tbody align="left">
        {% for record in record_list %}
        <tr>
            <td>{{ record['course_id'] }}</td>
            <td>{{ record['course_name'] }}</td>
            <td>{{ record['time'] }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/student/my.html
{% extends "base.html" %}
{% block title %}Attendance {% endblock %}
{% block page_content %}
<div class="container" style="text-align:center">
    <h1>学生个人信息</h1>
    <br>
    <p>学号：{{ student['stu_id'] }}</p>
    <p>姓名：{{ student['stu_name'] }}</p>
    <br>
    <a href="{{ url_for('student.join_course') }}" style="color:#000000; text-decoration:none;">
        <button type="button" class="btn btn-default">选课</button>
    </a>
    &emsp;
    <a href="{{ url_for('student.list_check_in_record') }}" style="color:#000000;">
        <button type="button" class="btn btn-default">签到记录</button>
    </a>
    <table class="table table-hover">
        <caption>已选课程</caption>
        <thead>
        <tr>
            <th>课程号</th>
            <th>课程名</th>
            <th>教师</th>
            <th>退课</th>
        </tr>
        </thead>
        <tbody align="left">
        {% for course in course_list %}
        <tr>
            <td>{{ course['course_id'] }}</td>
            <td>{{ course['course_name'] }}</td>
            <td>{{ course['teacher_name'] }}</td>
            <td><a style="color:#000000;">
                <button type="button" class="btn btn-default btn-xs"
                        onclick="quit_course({{ course['course_id'] }})">退课
                </button>
            </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript">
        function quit_course(course_id) {
            jQuery.ajax({
                url: '/student/quit_course',
                dataType: "json",
                data: JSON.stringify({
                    "course_id": course_id,
                }),
                cache: false,
                contentType: "application/json",
                processData: false,
                method: 'POST',
                type: 'POST', // For jQuery < 1.9
                success: function (data) {
                    if (data.result == 'ok') {
                        window.location.reload()
                    }
                }
            });
        }

</script>
{% endblock %}