app/teacher/__init__.py
from flask import Blueprint

teacher = Blueprint('teacher', __name__)

from . import views

app/teacher/views.py
import qrcode
import base64
import io
from flask import render_template, redirect, url_for, flash
from flask_login import login_required, current_user

from app import myUtils
from app.data.dao.impl.DaoImpl import DaoImpl
from config import *
from manage import config_name
from . import teacher

# 个人主页
from .form import CheckInTaskForm, EditInfoForm, CreateCourseForm

USER_TYPE = 'teacher'
HOME_PAGE = 'main.index'
NO_PERMISSION_TEXT = '没有访问权限.'


@teacher.route('/my')
@login_required
def my():
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    print('uuid:' + uuid)
    teacher = DaoImpl.query_teacher_by_uuid(uuid)
    # 不存在该教师信息
    if teacher is None:
        flash('请完善个人信息.')
        return redirect(url_for('teacher.edit_info'))
    # 获取课程列表
    course_list = DaoImpl.query_course_by_teacher_id(teacher.teacher_id)

    return render_template('teacher/my.html', teacher=teacher, course_list=course_list)


# 个人信息编辑页面
@teacher.route('/edit_info', methods=['GET', 'POST'])
@login_required
def edit_info():
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    teacher_id = myUtils.get_user_id(uuid)
    form = EditInfoForm()
    if form.validate_on_submit():
        teacher_name = form.teacher_name.data
        phone_number = form.phone_number.data
        email = form.email.data
        teacher = DaoImpl.query_teacher_by_uuid(uuid)
        # 存在该教师信息，修改
        if teacher:
            DaoImpl.update_teacher_by_uuid(uuid, teacher_name, phone_number, email)
        # 不存在该教师信息，插入
        else:
            DaoImpl.add_teacher(uuid, teacher_id, teacher_name, phone_number, email)
        flash('编辑成功.')
        return redirect(url_for('teacher.my'))

    return render_template('teacher/edit_info.html', teacher_id=teacher_id, form=form)


# 创建课程
@teacher.route('/create_course', methods=['GET', 'POST'])
@login_required
def create_course():
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    uuid = current_user.uuid
    teacher_id = myUtils.get_user_id(uuid)
    form = CreateCourseForm()
    if form.validate_on_submit():
        course_id = form.course_id.data
        course_name = form.course_name.data
        course_intro = form.course_intro.data
        DaoImpl.add_course(course_id, course_name, course_intro, teacher_id)
        flash('课程创建成功.')
        return redirect(url_for('teacher.my'))

    return render_template('teacher/create_course.html', form=form)


# 查看选课学生名单
@teacher.route('/list_student/<course_id>')
@login_required
def list_student(course_id):
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    course = DaoImpl.query_course_by_course_id(course_id)
    student_list = DaoImpl.query_student_by_course_id(course_id)

    return render_template('teacher/list_student.html', course=course, student_list=student_list)


# 查看签到任务
@teacher.route('/list_check_in/<course_id>')
@login_required
def list_check_in(course_id):
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    course = DaoImpl.query_course_by_course_id(course_id)
    task_list = DaoImpl.query_task_by_course_id(course_id)
    return render_template('teacher/list_check_in.html', task_list=task_list, course=course)


# 查看签到情况
@teacher.route('/list_check_in_student/<task_id>')
@login_required
def list_check_in_student(task_id):
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    task = DaoImpl.query_task_by_task_id(task_id)
    course = DaoImpl.query_course_by_course_id(task.course_id)
    check_in_stu_list = DaoImpl.query_check_in_record_for_teacher_by_task_id_and_course_id(task_id,
                                                                                           task.course_id)
    uncheck_in_stu_list = DaoImpl.query_student_by_task_id_and_course_id(task_id, task.course_id)
    return render_template('teacher/list_check_in_student.html', task=task, course=course,
                           check_in_stu_list=check_in_stu_list, uncheck_in_stu_list=uncheck_in_stu_list)


# 发布签到任务
@teacher.route('/create_check_in/<course_id>', methods=['GET', 'POST'])
@login_required
def create_check_in(course_id):
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    form = CheckInTaskForm()
    if form.validate_on_submit():
        print(type(form.start_time))
        start_time = form.start_time.data
        end_time = form.end_time.data
        DaoImpl.add_check_in_task(course_id, start_time, end_time)
        flash('发布成功.')
        return redirect(url_for('teacher.list_check_in', course_id=course_id))

    course = DaoImpl.query_course_by_course_id(course_id)
    return render_template('teacher/create_check_in.html', form=form, course=course)


# 查看签到二维码
@teacher.route('/check_in_code/<course_id>')
@login_required
def check_in_code(course_id):
    if current_user.user_type != USER_TYPE:
        flash(NO_PERMISSION_TEXT)
        return redirect(url_for(HOME_PAGE))
    course = DaoImpl.query_course_by_course_id(course_id)
    # 二维码
    check_in_url = url_for('student.check_in', course_id=course_id, _external=True)
    img = qrcode.make(check_in_url)
    # creates qrcode base64
    out = io.BytesIO()
    img.save(out, 'PNG')
    img_stream = u"data:image/png;base64," + base64.b64encode(out.getvalue()).decode('ascii')

    return render_template('teacher/check_in_code.html', img_stream=img_stream, course=course)

app/templates/teacher/check_in_code.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - code{% endblock %}

{% block page_content %}
    <div style="text-align:center">
        <h3>扫描二维码进行签到</h3>
        <img style="width:20em;" src="{{ img_stream }}">
        <br><br><br>
        <p>课程名：{{ course.course_name }}</p>
        <p>课程号：{{ course.course_id }}</p>
    </div>
{% endblock  %}

app/templates/teacher/create_check_in.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - create_check_in{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>发布签到任务</h1>
    <p>课程名：{{ course['course_name'] }}</p>
    <p>课程号：{{ course['course_id'] }}</p>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
    <br>
</div>

{% endblock  %}

{% block scripts %}
{{ super() }}
<script type="text/javascript">

        $('#start_time').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:00',
            locale: moment.locale('zh-cn'),
            defaultDate: "2020-5-15 8:00:00"
        });
        $('#end_time').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:00',
            locale: moment.locale('zh-cn'),
            defaultDate: "2020-05-15 9:00:00"
        });

</script>
{% endblock %}

app/templates/teacher/create_course.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - Edit{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>创建课程</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
    <br>
</div>
{% endblock %}

app/templates/teacher/edit_info.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - Edit{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>教师个人信息修改</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
    <br>
</div>
{% endblock %}

app/templates/teacher/list_check_in.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - Edit{% endblock %}

{% block page_content %}
<div class="page-header" style="text-align:center">
    <h1>查看签到任务</h1>
    <p>课程名：{{ course['course_name'] }}</p>
    <p>课程号：{{ course['course_id'] }}</p>
    <a style="color:#000000" href="{{ url_for('teacher.check_in_code',course_id = course['course_id']) }}">
        <button type="button" class="btn btn-default btn-xs" style="font-size:20px">签到二维码</button>
    </a>
</div>
<div>
    <table class="table table-hover">
        <caption>签到查看</caption>
        <thead>
        <tr>
            <th>签到任务ID</th>
            <th>起始时间</th>
            <th>结束时间</th>
            <th>学生签到情况</th>
        </tr>
        </thead>
        <tbody align="left">
        {% for task in task_list %}
        <tr>
            <td>{{ task['task_id'] }}</td>
            <td>{{ task['start_time'] }}</td>
            <td>{{ task['end_time'] }}</td>
            <td><a style="color:#000000;"
                   href="{{ url_for('teacher.list_check_in_student',task_id = task['task_id']) }}">
                <button type="button" class="btn btn-default btn-xs">签到情况</button>
            </a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/teacher/list_check_in_student.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - student_check{% endblock %}

{% block page_content %}
<div class="page-header" style="text-align:center">
    <h1>签到情况</h1>
    <br>
    <p>课程名称：{{ course['course_name'] }}</p>
    <p>课程号：{{ course['course_id'] }}</p>
    <p>签到任务ID：{{ task['task_id'] }}</p>
    <p>签到开始时间：{{ task['start_time'] }}</p>
    <p>签到结束时间：{{ task['end_time'] }}</p>
    <br>
    <p>签到率：
        {% if (check_in_stu_list | length) + (uncheck_in_stu_list | length) == 0 %}
        0%</p>
        {% else %}
        {{ (check_in_stu_list | length) / ((check_in_stu_list | length) + (uncheck_in_stu_list | length)) * 100
        }}%</p>
        {% endif %}

</div>
<div>
    <table class="table table-hover">
        <caption>已签到学生数量：{{ check_in_stu_list | length }}</caption>
        <thead>
        <tr>
            <th>学生ID</th>
            <th>学生姓名</th>
            <th>签到时间</th>
        </tr>
        </thead>
        <tbody align="left">
        {% for student in check_in_stu_list %}
        <tr>
            <td>{{ student['stu_id'] }}</td>
            <td>{{ student['stu_name'] }}</td>
            <td>{{ student['time'] }}</td>
        </tr>
        {% endfor %}
    </table>
    <table class="table table-hover">
        <caption>未签到学生数量：{{ uncheck_in_stu_list | length }}</caption>
        <thead>
        <tr>
            <th>学号</th>
            <th>学生姓名</th>
        </tr>
        </thead>
        <tbody align="left">
        {% for student in uncheck_in_stu_list %}
        <tr>
            <td>{{ student['stu_id'] }}</td>
            <td>{{ student['stu_name'] }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/teacher/list_student.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Attendance  - student_list{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>选课学生名单</h1>
</div>
<div>
    <table class="table table-hover">
        <caption>课程号：{{ course['course_id'] }}
            <br>
            课程名称：{{ course['course_name'] }}
        </caption>
        <thead>
        <tr>
            <th>学号</th>
            <th>学生姓名</th>
        </tr>
        </thead>
        <tbody align="left">
        {% for stu in student_list %}
        <tr>
            <td>{{ stu['stu_id'] }}</td>
            <td>{{ stu['stu_name'] }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/teacher/my.html
{% extends "base.html" %}
{% block title %}Attendance {% endblock %}
{% block page_content %}
<div class="container" style="text-align:center">
    <h1>个人主页</h1>
    <p>工号：{{ teacher['teacher_id'] }}</p>
    <p>姓名：{{ teacher['teacher_name'] }}</p>
    <br>
    <a href="{{ url_for('teacher.create_course') }}" style="color:#000000;">
        <button type="button" class="btn btn-default">创建课程</button>
    </a>
    <table class="table table-hover">
        <caption>您的课程</caption>
        <thead>
        <tr>
            <th>课程号</th>
            <th>课程名</th>
            <th>发布签到</th>
            <th>签到任务</th>
            <th>选课名单</th>
        </tr>
        </thead>
        <tbody align="left">
        {% for course in course_list %}
        <tr>
            <td>{{ course['course_id'] }}</td>
            <td>{{ course['course_name'] }}</td>
            <td><a style="color:#000000;"
                   href="{{ url_for('teacher.create_check_in',course_id=course['course_id']) }}">
                <button type="button" class="btn btn-default btn-xs">发布签到</button>
            </a></td>
            <td><a style="color:#000000;"
                   href="{{ url_for('teacher.list_check_in',course_id=course['course_id']) }}">
                <button type="button" class="btn btn-default btn-xs">签到任务</button>
            </a></td>
            <td><a style="color:#000000;"
                   href="{{ url_for('teacher.list_student',course_id=course['course_id']) }}">
                <button type="button" class="btn btn-default btn-xs">选课名单</button>
            </a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}